[project]
name = "rss-to-signal"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "feedparser>=6.0.11",
    "python-dateutil>=2.9.0.post0",
    "typer>=0.16.0",
]
